// 第三批次增量新增單字腳本 - 執行: node seed-batch3.js
require('dotenv').config();
const mongoose = require('mongoose');
const Vocabulary = require('./models/Vocabulary');

const MONGODB_URI = (process.env.MONGODB_URI || '').trim().replace(/ㄦ/g, '-');
if (!MONGODB_URI) { console.error('請設定 MONGODB_URI'); process.exit(1); }

const newWords = [
  // ===== A1 - Basic Adjectives =====
  { word: 'big', pronunciation: '/bɪɡ/', partOfSpeech: 'adjective', translation: '大的', explanation: 'Of large size.', examples: [{ sentence: 'It\'s a big house.', translation: '那是一棟大房子。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'small', pronunciation: '/smɔːl/', partOfSpeech: 'adjective', translation: '小的', explanation: 'Of little size.', examples: [{ sentence: 'The puppy is very small.', translation: '這隻小狗非常小。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'tall', pronunciation: '/tɔːl/', partOfSpeech: 'adjective', translation: '高的', explanation: 'Having greater than usual height.', examples: [{ sentence: 'He is very tall.', translation: '他非常高。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'short', pronunciation: '/ʃɔːrt/', partOfSpeech: 'adjective', translation: '矮的；短的', explanation: 'Of little height or length.', examples: [{ sentence: 'She has short hair.', translation: '她有短髮。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'long', pronunciation: '/lɒŋ/', partOfSpeech: 'adjective', translation: '長的', explanation: 'Having great length.', examples: [{ sentence: 'The road is very long.', translation: '這條路很長。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'wide', pronunciation: '/waɪd/', partOfSpeech: 'adjective', translation: '寬的', explanation: 'Having a large distance from side to side.', examples: [{ sentence: 'The river is wide.', translation: '這條河很寬。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'narrow', pronunciation: '/ˈnæroʊ/', partOfSpeech: 'adjective', translation: '窄的', explanation: 'Having a small distance from side to side.', examples: [{ sentence: 'The street is very narrow.', translation: '這條街非常窄。' }], level: 'A1', tags: ['adjective', 'size'] },
  { word: 'heavy', pronunciation: '/ˈhɛvi/', partOfSpeech: 'adjective', translation: '重的', explanation: 'Of great weight.', examples: [{ sentence: 'The box is heavy.', translation: '這個箱子很重。' }], level: 'A1', tags: ['adjective'] },
  { word: 'light', pronunciation: '/laɪt/', partOfSpeech: 'adjective', translation: '輕的；亮的', explanation: 'Not heavy; having brightness.', examples: [{ sentence: 'This bag is light.', translation: '這個包很輕。' }], level: 'A1', tags: ['adjective'] },
  { word: 'fast', pronunciation: '/fæst/', partOfSpeech: 'adjective', translation: '快的', explanation: 'Moving at high speed.', examples: [{ sentence: 'He is a fast runner.', translation: '他是一個跑得很快的人。' }], level: 'A1', tags: ['adjective', 'speed'] },
  { word: 'slow', pronunciation: '/sloʊ/', partOfSpeech: 'adjective', translation: '慢的', explanation: 'Not moving quickly.', examples: [{ sentence: 'The bus is very slow.', translation: '公車非常慢。' }], level: 'A1', tags: ['adjective', 'speed'] },
  { word: 'loud', pronunciation: '/laʊd/', partOfSpeech: 'adjective', translation: '大聲的', explanation: 'Making a great noise.', examples: [{ sentence: 'The music is too loud.', translation: '音樂太大聲了。' }], level: 'A1', tags: ['adjective'] },
  { word: 'quiet', pronunciation: '/ˈkwaɪɪt/', partOfSpeech: 'adjective', translation: '安靜的', explanation: 'Making little or no noise.', examples: [{ sentence: 'Please be quiet.', translation: '請安靜。' }], level: 'A1', tags: ['adjective'] },
  { word: 'clean', pronunciation: '/kliːn/', partOfSpeech: 'adjective', translation: '乾淨的', explanation: 'Free from dirt.', examples: [{ sentence: 'The room is clean.', translation: '房間很乾淨。' }], level: 'A1', tags: ['adjective'] },
  { word: 'dirty', pronunciation: '/ˈdɜːrti/', partOfSpeech: 'adjective', translation: '髒的', explanation: 'Not clean.', examples: [{ sentence: 'Your hands are dirty.', translation: '你的手很髒。' }], level: 'A1', tags: ['adjective'] },
  { word: 'full', pronunciation: '/fʊl/', partOfSpeech: 'adjective', translation: '滿的', explanation: 'Containing the most possible.', examples: [{ sentence: 'The glass is full.', translation: '杯子是滿的。' }], level: 'A1', tags: ['adjective'] },
  { word: 'empty', pronunciation: '/ˈɛmpti/', partOfSpeech: 'adjective', translation: '空的', explanation: 'Containing nothing.', examples: [{ sentence: 'The box is empty.', translation: '箱子是空的。' }], level: 'A1', tags: ['adjective'] },
  { word: 'right', pronunciation: '/raɪt/', partOfSpeech: 'adjective', translation: '正確的；右邊的', explanation: 'Correct; on the right side.', examples: [{ sentence: 'That\'s the right answer.', translation: '那是正確答案。' }], level: 'A1', tags: ['adjective', 'direction'] },
  { word: 'wrong', pronunciation: '/rɒŋ/', partOfSpeech: 'adjective', translation: '錯誤的', explanation: 'Not correct.', examples: [{ sentence: 'That answer is wrong.', translation: '那個答案是錯的。' }], level: 'A1', tags: ['adjective'] },
  { word: 'same', pronunciation: '/seɪm/', partOfSpeech: 'adjective', translation: '相同的', explanation: 'Identical; not different.', examples: [{ sentence: 'We have the same birthday.', translation: '我們生日相同。' }], level: 'A1', tags: ['adjective'] },
  { word: 'different', pronunciation: '/ˈdɪfrənt/', partOfSpeech: 'adjective', translation: '不同的', explanation: 'Not the same.', examples: [{ sentence: 'We like different foods.', translation: '我們喜歡不同的食物。' }], level: 'A1', tags: ['adjective'] },

  // ===== A1 - Basic Verbs =====
  { word: 'run', pronunciation: '/rʌn/', partOfSpeech: 'verb', translation: '跑', explanation: 'To move at a fast pace.', examples: [{ sentence: 'I run every morning.', translation: '我每天早上跑步。' }], level: 'A1', tags: ['verb', 'sport'] },
  { word: 'walk', pronunciation: '/wɔːk/', partOfSpeech: 'verb', translation: '走路', explanation: 'To move by foot at a normal pace.', examples: [{ sentence: 'I walk to school.', translation: '我走路去學校。' }], level: 'A1', tags: ['verb'] },
  { word: 'jump', pronunciation: '/dʒʌmp/', partOfSpeech: 'verb', translation: '跳', explanation: 'To move into the air.', examples: [{ sentence: 'The cat jumped over the wall.', translation: '貓跳過了牆。' }], level: 'A1', tags: ['verb'] },
  { word: 'sit', pronunciation: '/sɪt/', partOfSpeech: 'verb', translation: '坐', explanation: 'To rest on a seat.', examples: [{ sentence: 'Please sit down.', translation: '請坐下。' }], level: 'A1', tags: ['verb'] },
  { word: 'stand', pronunciation: '/stænd/', partOfSpeech: 'verb', translation: '站立', explanation: 'To be in an upright position.', examples: [{ sentence: 'Please stand up.', translation: '請站起來。' }], level: 'A1', tags: ['verb'] },
  { word: 'sleep', pronunciation: '/sliːp/', partOfSpeech: 'verb', translation: '睡覺', explanation: 'To rest with eyes closed.', examples: [{ sentence: 'I sleep eight hours a night.', translation: '我每晚睡八個小時。' }], level: 'A1', tags: ['verb'] },
  { word: 'wake', pronunciation: '/weɪk/', partOfSpeech: 'verb', translation: '醒來', explanation: 'To stop sleeping.', examples: [{ sentence: 'I wake up at 7 am.', translation: '我早上七點起床。' }], level: 'A1', tags: ['verb'] },
  { word: 'cook', pronunciation: '/kʊk/', partOfSpeech: 'verb', translation: '烹飪', explanation: 'To prepare food using heat.', examples: [{ sentence: 'My mom cooks dinner every night.', translation: '我媽媽每晚煮晚餐。' }], level: 'A1', tags: ['verb', 'food'] },
  { word: 'drink', pronunciation: '/drɪŋk/', partOfSpeech: 'verb', translation: '喝', explanation: 'To swallow liquid.', examples: [{ sentence: 'Drink plenty of water.', translation: '多喝水。' }], level: 'A1', tags: ['verb', 'food'] },
  { word: 'eat', pronunciation: '/iːt/', partOfSpeech: 'verb', translation: '吃', explanation: 'To put food in your mouth and swallow it.', examples: [{ sentence: 'I eat breakfast at seven.', translation: '我七點吃早餐。' }], level: 'A1', tags: ['verb', 'food'] },
  { word: 'drive', pronunciation: '/draɪv/', partOfSpeech: 'verb', translation: '駕駛', explanation: 'To operate a vehicle.', examples: [{ sentence: 'She drives to work.', translation: '她開車上班。' }], level: 'A1', tags: ['verb', 'transport'] },
  { word: 'swim', pronunciation: '/swɪm/', partOfSpeech: 'verb', translation: '游泳', explanation: 'To move through water using body movements.', examples: [{ sentence: 'I swim on weekends.', translation: '我週末游泳。' }], level: 'A1', tags: ['verb', 'sport'] },
  { word: 'dance', pronunciation: '/dæns/', partOfSpeech: 'verb', translation: '跳舞', explanation: 'To move rhythmically to music.', examples: [{ sentence: 'She loves to dance.', translation: '她喜歡跳舞。' }], level: 'A1', tags: ['verb', 'art'] },
  { word: 'sing', pronunciation: '/sɪŋ/', partOfSpeech: 'verb', translation: '唱歌', explanation: 'To make music with your voice.', examples: [{ sentence: 'She sings beautifully.', translation: '她唱歌很好聽。' }], level: 'A1', tags: ['verb', 'art'] },
  { word: 'draw', pronunciation: '/drɔː/', partOfSpeech: 'verb', translation: '畫畫', explanation: 'To create pictures with a pencil or pen.', examples: [{ sentence: 'He can draw very well.', translation: '他畫得很好。' }], level: 'A1', tags: ['verb', 'art'] },
  { word: 'write', pronunciation: '/raɪt/', partOfSpeech: 'verb', translation: '寫', explanation: 'To form letters or words on a surface.', examples: [{ sentence: 'Write your name here.', translation: '在這裡寫你的名字。' }], level: 'A1', tags: ['verb'] },
  { word: 'read', pronunciation: '/riːd/', partOfSpeech: 'verb', translation: '閱讀', explanation: 'To look at and understand written text.', examples: [{ sentence: 'I read every night.', translation: '我每晚閱讀。' }], level: 'A1', tags: ['verb'] },
  { word: 'study', pronunciation: '/ˈstʌdi/', partOfSpeech: 'verb', translation: '學習；讀書', explanation: 'To spend time learning.', examples: [{ sentence: 'I study English every day.', translation: '我每天學英文。' }], level: 'A1', tags: ['verb', 'education'] },
  { word: 'play', pronunciation: '/pleɪ/', partOfSpeech: 'verb', translation: '玩；演奏', explanation: 'To engage in activity for fun.', examples: [{ sentence: 'Children love to play.', translation: '孩子喜歡玩耍。' }], level: 'A1', tags: ['verb', 'sport', 'art'] },
  { word: 'watch', pronunciation: '/wɒtʃ/', partOfSpeech: 'verb', translation: '看；觀看', explanation: 'To look at something carefully.', examples: [{ sentence: 'I watch TV in the evening.', translation: '我晚上看電視。' }], level: 'A1', tags: ['verb'] },
  { word: 'listen', pronunciation: '/ˈlɪsən/', partOfSpeech: 'verb', translation: '聽', explanation: 'To pay attention to sounds.', examples: [{ sentence: 'Listen to me carefully.', translation: '仔細聽我說。' }], level: 'A1', tags: ['verb'] },
  { word: 'speak', pronunciation: '/spiːk/', partOfSpeech: 'verb', translation: '說話', explanation: 'To say words out loud.', examples: [{ sentence: 'Can you speak more slowly?', translation: '你能說慢一點嗎？' }], level: 'A1', tags: ['verb', 'communication'] },
  { word: 'call', pronunciation: '/kɔːl/', partOfSpeech: 'verb', translation: '打電話；叫', explanation: 'To phone someone; to shout.', examples: [{ sentence: 'Call me tonight.', translation: '今晚打電話給我。' }], level: 'A1', tags: ['verb', 'communication'] },
  { word: 'answer', pronunciation: '/ˈænsər/', partOfSpeech: 'verb', translation: '回答', explanation: 'To respond to a question.', examples: [{ sentence: 'Please answer my question.', translation: '請回答我的問題。' }], level: 'A1', tags: ['verb', 'communication'] },
  { word: 'ask', pronunciation: '/æsk/', partOfSpeech: 'verb', translation: '問', explanation: 'To request information.', examples: [{ sentence: 'Can I ask you something?', translation: '我可以問你一件事嗎？' }], level: 'A1', tags: ['verb', 'communication'] },
  { word: 'give', pronunciation: '/ɡɪv/', partOfSpeech: 'verb', translation: '給', explanation: 'To hand something to someone.', examples: [{ sentence: 'Give me your hand.', translation: '給我你的手。' }], level: 'A1', tags: ['verb'] },
  { word: 'take', pronunciation: '/teɪk/', partOfSpeech: 'verb', translation: '拿；帶', explanation: 'To grab or carry something.', examples: [{ sentence: 'Take an umbrella with you.', translation: '帶一把傘出門。' }], level: 'A1', tags: ['verb'] },
  { word: 'bring', pronunciation: '/brɪŋ/', partOfSpeech: 'verb', translation: '帶來', explanation: 'To carry something to a place.', examples: [{ sentence: 'Bring your ID card.', translation: '帶你的身分證。' }], level: 'A1', tags: ['verb'] },
  { word: 'put', pronunciation: '/pʊt/', partOfSpeech: 'verb', translation: '放', explanation: 'To place something in a position.', examples: [{ sentence: 'Put the book on the table.', translation: '把書放在桌上。' }], level: 'A1', tags: ['verb'] },
  { word: 'get', pronunciation: '/ɡɛt/', partOfSpeech: 'verb', translation: '得到；拿到', explanation: 'To receive or obtain something.', examples: [{ sentence: 'I got a good grade.', translation: '我得了高分。' }], level: 'A1', tags: ['verb'] },
  { word: 'make', pronunciation: '/meɪk/', partOfSpeech: 'verb', translation: '製作；做', explanation: 'To create or produce something.', examples: [{ sentence: 'Let\'s make a cake.', translation: '我們來做蛋糕吧。' }], level: 'A1', tags: ['verb'] },
  { word: 'use', pronunciation: '/juːz/', partOfSpeech: 'verb', translation: '使用', explanation: 'To employ something for a purpose.', examples: [{ sentence: 'Use a pencil to write.', translation: '用鉛筆寫字。' }], level: 'A1', tags: ['verb'] },
  { word: 'find', pronunciation: '/faɪnd/', partOfSpeech: 'verb', translation: '找到', explanation: 'To locate something.', examples: [{ sentence: 'I can\'t find my keys.', translation: '我找不到鑰匙。' }], level: 'A1', tags: ['verb'] },
  { word: 'lose', pronunciation: '/luːz/', partOfSpeech: 'verb', translation: '失去；輸', explanation: 'To be unable to find something; to be defeated.', examples: [{ sentence: 'Don\'t lose your ticket.', translation: '不要遺失你的票。' }], level: 'A1', tags: ['verb'] },
  { word: 'open', pronunciation: '/ˈoʊpən/', partOfSpeech: 'verb', translation: '打開', explanation: 'To make accessible.', examples: [{ sentence: 'Open the window.', translation: '打開窗戶。' }], level: 'A1', tags: ['verb'] },
  { word: 'close', pronunciation: '/kloʊz/', partOfSpeech: 'verb', translation: '關閉', explanation: 'To shut or seal.', examples: [{ sentence: 'Close the door quietly.', translation: '輕輕關門。' }], level: 'A1', tags: ['verb'] },
  { word: 'start', pronunciation: '/stɑːrt/', partOfSpeech: 'verb', translation: '開始', explanation: 'To begin an activity.', examples: [{ sentence: 'Let\'s start the meeting.', translation: '我們開始會議吧。' }], level: 'A1', tags: ['verb'] },
  { word: 'stop', pronunciation: '/stɒp/', partOfSpeech: 'verb', translation: '停止', explanation: 'To cease doing something.', examples: [{ sentence: 'Stop talking!', translation: '停止說話！' }], level: 'A1', tags: ['verb'] },
  { word: 'wait', pronunciation: '/weɪt/', partOfSpeech: 'verb', translation: '等待', explanation: 'To stay until something happens.', examples: [{ sentence: 'Wait for me!', translation: '等我！' }], level: 'A1', tags: ['verb'] },
  { word: 'try', pronunciation: '/traɪ/', partOfSpeech: 'verb', translation: '嘗試', explanation: 'To make an attempt.', examples: [{ sentence: 'Try again!', translation: '再試一次！' }], level: 'A1', tags: ['verb'] },
  { word: 'need', pronunciation: '/niːd/', partOfSpeech: 'verb', translation: '需要', explanation: 'To require something.', examples: [{ sentence: 'I need your help.', translation: '我需要你的幫助。' }], level: 'A1', tags: ['verb'] },
  { word: 'want', pronunciation: '/wɒnt/', partOfSpeech: 'verb', translation: '想要', explanation: 'To desire something.', examples: [{ sentence: 'I want a glass of water.', translation: '我想要一杯水。' }], level: 'A1', tags: ['verb'] },
  { word: 'help', pronunciation: '/hɛlp/', partOfSpeech: 'verb', translation: '幫助', explanation: 'To assist someone.', examples: [{ sentence: 'Can you help me?', translation: '你能幫我嗎？' }], level: 'A1', tags: ['verb'] },
  { word: 'know', pronunciation: '/noʊ/', partOfSpeech: 'verb', translation: '知道；了解', explanation: 'To have knowledge of.', examples: [{ sentence: 'Do you know the answer?', translation: '你知道答案嗎？' }], level: 'A1', tags: ['verb'] },
  { word: 'think', pronunciation: '/θɪŋk/', partOfSpeech: 'verb', translation: '認為；思考', explanation: 'To use the mind to form ideas.', examples: [{ sentence: 'Think before you speak.', translation: '說話前先思考。' }], level: 'A1', tags: ['verb'] },
  { word: 'feel', pronunciation: '/fiːl/', partOfSpeech: 'verb', translation: '感覺', explanation: 'To experience an emotion.', examples: [{ sentence: 'I feel happy today.', translation: '我今天感覺很快樂。' }], level: 'A1', tags: ['verb'] },
  { word: 'see', pronunciation: '/siː/', partOfSpeech: 'verb', translation: '看見', explanation: 'To perceive with the eyes.', examples: [{ sentence: 'I can see a rainbow.', translation: '我能看到彩虹。' }], level: 'A1', tags: ['verb'] },
  { word: 'hear', pronunciation: '/hɪr/', partOfSpeech: 'verb', translation: '聽到', explanation: 'To perceive sound.', examples: [{ sentence: 'I can\'t hear you.', translation: '我聽不到你說話。' }], level: 'A1', tags: ['verb'] },
  { word: 'smell', pronunciation: '/smɛl/', partOfSpeech: 'verb', translation: '聞', explanation: 'To perceive odour.', examples: [{ sentence: 'I can smell food.', translation: '我聞到食物的味道。' }], level: 'A1', tags: ['verb'] },
  { word: 'show', pronunciation: '/ʃoʊ/', partOfSpeech: 'verb', translation: '展示；顯示', explanation: 'To make visible; to demonstrate.', examples: [{ sentence: 'Show me your homework.', translation: '給我看你的作業。' }], level: 'A1', tags: ['verb'] },
  { word: 'send', pronunciation: '/sɛnd/', partOfSpeech: 'verb', translation: '發送', explanation: 'To cause something to go somewhere.', examples: [{ sentence: 'Send me an email.', translation: '發電子郵件給我。' }], level: 'A1', tags: ['verb', 'communication'] },
  { word: 'receive', pronunciation: '/rɪˈsiːv/', partOfSpeech: 'verb', translation: '收到', explanation: 'To be given something.', examples: [{ sentence: 'I received a gift.', translation: '我收到了一份禮物。' }], level: 'A1', tags: ['verb'] },
  { word: 'pay', pronunciation: '/peɪ/', partOfSpeech: 'verb', translation: '付錢', explanation: 'To give money in exchange for goods.', examples: [{ sentence: 'I\'ll pay for dinner.', translation: '我來付晚餐的錢。' }], level: 'A1', tags: ['verb', 'money'] },
  { word: 'buy', pronunciation: '/baɪ/', partOfSpeech: 'verb', translation: '購買', explanation: 'To get something in exchange for money.', examples: [{ sentence: 'I want to buy a new phone.', translation: '我想買一支新手機。' }], level: 'A1', tags: ['verb', 'shopping'] },
  { word: 'sell', pronunciation: '/sɛl/', partOfSpeech: 'verb', translation: '賣', explanation: 'To exchange goods for money.', examples: [{ sentence: 'They sell fresh vegetables.', translation: '他們賣新鮮蔬菜。' }], level: 'A1', tags: ['verb', 'shopping'] },
  { word: 'turn', pronunciation: '/tɜːrn/', partOfSpeech: 'verb', translation: '轉動；轉向', explanation: 'To move in a circular direction.', examples: [{ sentence: 'Turn left at the corner.', translation: '在路口左轉。' }], level: 'A1', tags: ['verb', 'direction'] },
  { word: 'move', pronunciation: '/muːv/', partOfSpeech: 'verb', translation: '移動', explanation: 'To go from one place to another.', examples: [{ sentence: 'Please move your car.', translation: '請移動你的車。' }], level: 'A1', tags: ['verb'] },
  { word: 'carry', pronunciation: '/ˈkæri/', partOfSpeech: 'verb', translation: '攜帶', explanation: 'To hold and transport.', examples: [{ sentence: 'Can you carry this bag?', translation: '你能提這個包嗎？' }], level: 'A1', tags: ['verb'] },
  { word: 'throw', pronunciation: '/θroʊ/', partOfSpeech: 'verb', translation: '丟；投', explanation: 'To propel through the air.', examples: [{ sentence: 'Throw the ball to me.', translation: '把球丟給我。' }], level: 'A1', tags: ['verb', 'sport'] },
  { word: 'catch', pronunciation: '/kætʃ/', partOfSpeech: 'verb', translation: '抓住', explanation: 'To grab something moving through the air.', examples: [{ sentence: 'Catch the ball!', translation: '接住球！' }], level: 'A1', tags: ['verb', 'sport'] },

  // ===== A2 - Fruits & Vegetables =====
  { word: 'apple', pronunciation: '/ˈæpəl/', partOfSpeech: 'noun', translation: '蘋果', explanation: 'A round fruit with red or green skin.', examples: [{ sentence: 'An apple a day keeps the doctor away.', translation: '每天一蘋果，醫生遠離我。' }], level: 'A1', tags: ['food', 'fruit'] },
  { word: 'banana', pronunciation: '/bəˈnɑːnə/', partOfSpeech: 'noun', translation: '香蕉', explanation: 'A long curved yellow fruit.', examples: [{ sentence: 'I eat a banana for breakfast.', translation: '我早餐吃香蕉。' }], level: 'A1', tags: ['food', 'fruit'] },
  { word: 'orange', pronunciation: '/ˈɒrɪndʒ/', partOfSpeech: 'noun', translation: '柳橙', explanation: 'A round citrus fruit with orange skin.', examples: [{ sentence: 'This orange is very sweet.', translation: '這顆柳橙很甜。' }], level: 'A1', tags: ['food', 'fruit'] },
  { word: 'grape', pronunciation: '/ɡreɪp/', partOfSpeech: 'noun', translation: '葡萄', explanation: 'A small round fruit that grows in clusters.', examples: [{ sentence: 'I love eating grapes.', translation: '我喜歡吃葡萄。' }], level: 'A2', tags: ['food', 'fruit'] },
  { word: 'strawberry', pronunciation: '/ˈstrɔːbəri/', partOfSpeech: 'noun', translation: '草莓', explanation: 'A small red sweet fruit.', examples: [{ sentence: 'Strawberries are delicious with cream.', translation: '草莓加上鮮奶油很好吃。' }], level: 'A2', tags: ['food', 'fruit'] },
  { word: 'watermelon', pronunciation: '/ˈwɔːtərˌmɛlən/', partOfSpeech: 'noun', translation: '西瓜', explanation: 'A large fruit with green skin and red inside.', examples: [{ sentence: 'We eat watermelon in summer.', translation: '我們夏天吃西瓜。' }], level: 'A2', tags: ['food', 'fruit'] },
  { word: 'mango', pronunciation: '/ˈmæŋɡoʊ/', partOfSpeech: 'noun', translation: '芒果', explanation: 'A tropical fruit with sweet orange flesh.', examples: [{ sentence: 'Taiwan\'s mangoes are famous.', translation: '台灣的芒果很有名。' }], level: 'A2', tags: ['food', 'fruit'] },
  { word: 'lemon', pronunciation: '/ˈlɛmən/', partOfSpeech: 'noun', translation: '檸檬', explanation: 'A sour yellow citrus fruit.', examples: [{ sentence: 'Add lemon to your water.', translation: '在水中加檸檬。' }], level: 'A2', tags: ['food', 'fruit'] },
  { word: 'tomato', pronunciation: '/təˈmɑːtoʊ/', partOfSpeech: 'noun', translation: '番茄', explanation: 'A red or yellow fruit used as a vegetable.', examples: [{ sentence: 'I added tomato to the salad.', translation: '我在沙拉裡加了番茄。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'carrot', pronunciation: '/ˈkærət/', partOfSpeech: 'noun', translation: '紅蘿蔔', explanation: 'An orange root vegetable.', examples: [{ sentence: 'Rabbits like carrots.', translation: '兔子喜歡紅蘿蔔。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'potato', pronunciation: '/pəˈteɪtoʊ/', partOfSpeech: 'noun', translation: '馬鈴薯', explanation: 'A starchy root vegetable.', examples: [{ sentence: 'I love baked potato.', translation: '我喜歡烤馬鈴薯。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'onion', pronunciation: '/ˈʌnjən/', partOfSpeech: 'noun', translation: '洋蔥', explanation: 'A round vegetable with a strong flavour.', examples: [{ sentence: 'Onions make me cry.', translation: '洋蔥讓我流淚。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'garlic', pronunciation: '/ˈɡɑːrlɪk/', partOfSpeech: 'noun', translation: '大蒜', explanation: 'A bulb used as flavouring in cooking.', examples: [{ sentence: 'Add garlic to the sauce.', translation: '在醬汁裡加大蒜。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'mushroom', pronunciation: '/ˈmʌʃruːm/', partOfSpeech: 'noun', translation: '蘑菇', explanation: 'A type of fungus used as food.', examples: [{ sentence: 'I love mushroom soup.', translation: '我喜歡蘑菇湯。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'spinach', pronunciation: '/ˈspɪnɪtʃ/', partOfSpeech: 'noun', translation: '菠菜', explanation: 'A dark green leafy vegetable.', examples: [{ sentence: 'Spinach is rich in iron.', translation: '菠菜富含鐵質。' }], level: 'A2', tags: ['food', 'vegetable'] },
  { word: 'corn', pronunciation: '/kɔːrn/', partOfSpeech: 'noun', translation: '玉米', explanation: 'A yellow grain vegetable.', examples: [{ sentence: 'I love eating corn on the cob.', translation: '我喜歡啃玉米棒。' }], level: 'A2', tags: ['food', 'vegetable'] },

  // ===== A2 - Sports =====
  { word: 'football', pronunciation: '/ˈfʊtbɔːl/', partOfSpeech: 'noun', translation: '足球', explanation: 'A team sport played with a round ball.', examples: [{ sentence: 'He plays football every weekend.', translation: '他每週末踢足球。' }], level: 'A2', tags: ['sport'] },
  { word: 'basketball', pronunciation: '/ˈbɑːskɪtbɔːl/', partOfSpeech: 'noun', translation: '籃球', explanation: 'A sport where players throw balls into a hoop.', examples: [{ sentence: 'I play basketball with my friends.', translation: '我和朋友打籃球。' }], level: 'A2', tags: ['sport'] },
  { word: 'tennis', pronunciation: '/ˈtɛnɪs/', partOfSpeech: 'noun', translation: '網球', explanation: 'A sport played with rackets over a net.', examples: [{ sentence: 'She plays tennis every day.', translation: '她每天打網球。' }], level: 'A2', tags: ['sport'] },
  { word: 'baseball', pronunciation: '/ˈbeɪsbɔːl/', partOfSpeech: 'noun', translation: '棒球', explanation: 'A sport played with a bat and ball.', examples: [{ sentence: 'Baseball is popular in Taiwan.', translation: '棒球在台灣很受歡迎。' }], level: 'A2', tags: ['sport'] },
  { word: 'volleyball', pronunciation: '/ˈvɒlibɔːl/', partOfSpeech: 'noun', translation: '排球', explanation: 'A sport where teams hit a ball over a net.', examples: [{ sentence: 'They play volleyball on the beach.', translation: '他們在海灘打排球。' }], level: 'A2', tags: ['sport'] },
  { word: 'cycling', pronunciation: '/ˈsaɪklɪŋ/', partOfSpeech: 'noun', translation: '騎自行車', explanation: 'The activity of riding a bicycle.', examples: [{ sentence: 'Cycling is good for health.', translation: '騎自行車對健康有益。' }], level: 'A2', tags: ['sport', 'transport'] },
  { word: 'hiking', pronunciation: '/ˈhaɪkɪŋ/', partOfSpeech: 'noun', translation: '健行', explanation: 'Walking for long distances in nature.', examples: [{ sentence: 'I go hiking on weekends.', translation: '我週末去健行。' }], level: 'A2', tags: ['sport', 'nature'] },
  { word: 'yoga', pronunciation: '/ˈjoʊɡə/', partOfSpeech: 'noun', translation: '瑜伽', explanation: 'An exercise system using postures and breathing.', examples: [{ sentence: 'She does yoga every morning.', translation: '她每天早上做瑜伽。' }], level: 'A2', tags: ['sport', 'health'] },

  // ===== B1 - Media & Entertainment =====
  { word: 'magazine', pronunciation: '/ˌmæɡəˈziːn/', partOfSpeech: 'noun', translation: '雜誌', explanation: 'A periodical publication with articles.', examples: [{ sentence: 'I subscribe to a fashion magazine.', translation: '我訂閱了一本時尚雜誌。' }], level: 'B1', tags: ['media'] },
  { word: 'newspaper', pronunciation: '/ˈnjuːzpeɪpər/', partOfSpeech: 'noun', translation: '報紙', explanation: 'A daily printed publication with news.', examples: [{ sentence: 'My dad reads the newspaper.', translation: '我爸爸閱讀報紙。' }], level: 'A2', tags: ['media'] },
  { word: 'documentary', pronunciation: '/ˌdɒkjəˈmɛntəri/', partOfSpeech: 'noun', translation: '紀錄片', explanation: 'A film based on real events.', examples: [{ sentence: 'I watched a nature documentary.', translation: '我看了一部自然紀錄片。' }], level: 'B1', tags: ['media', 'entertainment'] },
  { word: 'series', pronunciation: '/ˈsɪəriːz/', partOfSpeech: 'noun', translation: '系列；影集', explanation: 'A set of TV programmes with the same characters.', examples: [{ sentence: 'I\'m watching a new series.', translation: '我在看一部新影集。' }], level: 'B1', tags: ['media', 'entertainment'] },
  { word: 'episode', pronunciation: '/ˈɛpɪsoʊd/', partOfSpeech: 'noun', translation: '集數；一集', explanation: 'One part of a TV series.', examples: [{ sentence: 'I watched three episodes last night.', translation: '我昨晚看了三集。' }], level: 'B1', tags: ['media', 'entertainment'] },
  { word: 'concert', pronunciation: '/ˈkɒnsərt/', partOfSpeech: 'noun', translation: '演唱會；音樂會', explanation: 'A live music performance.', examples: [{ sentence: 'We went to a rock concert.', translation: '我們去了搖滾演唱會。' }], level: 'B1', tags: ['entertainment', 'art'] },
  { word: 'exhibition', pronunciation: '/ˌɛksɪˈbɪʃən/', partOfSpeech: 'noun', translation: '展覽', explanation: 'A public display of art or objects.', examples: [{ sentence: 'I visited the art exhibition.', translation: '我參觀了藝術展覽。' }], level: 'B1', tags: ['art', 'entertainment'] },
  { word: 'performance', pronunciation: '/pərˈfɔːrməns/', partOfSpeech: 'noun', translation: '表演；演出', explanation: 'An act of performing before an audience.', examples: [{ sentence: 'The performance was excellent.', translation: '這場表演非常精彩。' }], level: 'B1', tags: ['art', 'entertainment'] },
  { word: 'audience', pronunciation: '/ˈɔːdiəns/', partOfSpeech: 'noun', translation: '觀眾；聽眾', explanation: 'A group watching or listening to a performance.', examples: [{ sentence: 'The audience applauded loudly.', translation: '觀眾大聲鼓掌。' }], level: 'B1', tags: ['entertainment', 'communication'] },
  { word: 'broadcast', pronunciation: '/ˈbrɔːdkæst/', partOfSpeech: 'verb', translation: '播出；廣播', explanation: 'To transmit a programme on TV or radio.', examples: [{ sentence: 'The match was broadcast live.', translation: '比賽現場直播。' }], level: 'B1', tags: ['media'] },

  // ===== B1 - Personality / Character =====
  { word: 'generous', pronunciation: '/ˈdʒɛnərəs/', partOfSpeech: 'adjective', translation: '慷慨的', explanation: 'Willing to give freely.', examples: [{ sentence: 'She is very generous with her time.', translation: '她在時間方面非常慷慨。' }], level: 'B1', tags: ['character'] },
  { word: 'selfish', pronunciation: '/ˈsɛlfɪʃ/', partOfSpeech: 'adjective', translation: '自私的', explanation: 'Caring only about oneself.', examples: [{ sentence: 'Don\'t be selfish.', translation: '不要自私。' }], level: 'B1', tags: ['character'] },
  { word: 'patient', pronunciation: '/ˈpeɪʃənt/', partOfSpeech: 'adjective', translation: '有耐心的', explanation: 'Able to wait calmly.', examples: [{ sentence: 'Be patient with beginners.', translation: '對初學者要有耐心。' }], level: 'B1', tags: ['character'] },
  { word: 'stubborn', pronunciation: '/ˈstʌbərn/', partOfSpeech: 'adjective', translation: '固執的', explanation: 'Refusing to change one\'s opinion.', examples: [{ sentence: 'He\'s too stubborn to admit mistakes.', translation: '他太固執，不肯承認錯誤。' }], level: 'B1', tags: ['character'] },
  { word: 'creative', pronunciation: '/kriˈeɪtɪv/', partOfSpeech: 'adjective', translation: '有創意的', explanation: 'Having the ability to create new ideas.', examples: [{ sentence: 'She is a very creative designer.', translation: '她是一位非常有創意的設計師。' }], level: 'B1', tags: ['character'] },
  { word: 'responsible', pronunciation: '/rɪˈspɒnsɪbəl/', partOfSpeech: 'adjective', translation: '負責任的', explanation: 'Having the duty to deal with something.', examples: [{ sentence: 'He is a responsible employee.', translation: '他是一個負責任的員工。' }], level: 'B1', tags: ['character', 'work'] },
  { word: 'reliable', pronunciation: '/rɪˈlaɪəbəl/', partOfSpeech: 'adjective', translation: '可靠的', explanation: 'Consistently good in quality; trustworthy.', examples: [{ sentence: 'She is a reliable friend.', translation: '她是一個可靠的朋友。' }], level: 'B1', tags: ['character'] },
  { word: 'ambitious', pronunciation: '/æmˈbɪʃəs/', partOfSpeech: 'adjective', translation: '有抱負的', explanation: 'Having a strong desire to succeed.', examples: [{ sentence: 'He is very ambitious.', translation: '他非常有抱負。' }], level: 'B1', tags: ['character'] },
  { word: 'honest', pronunciation: '/ˈɒnɪst/', partOfSpeech: 'adjective', translation: '誠實的', explanation: 'Truthful and fair.', examples: [{ sentence: 'Be honest with me.', translation: '對我誠實。' }], level: 'B1', tags: ['character'] },
  { word: 'optimistic', pronunciation: '/ˌɒptɪˈmɪstɪk/', partOfSpeech: 'adjective', translation: '樂觀的', explanation: 'Expecting good things to happen.', examples: [{ sentence: 'Try to be optimistic.', translation: '試著保持樂觀。' }], level: 'B1', tags: ['character', 'emotion'] },
  { word: 'pessimistic', pronunciation: '/ˌpɛsɪˈmɪstɪk/', partOfSpeech: 'adjective', translation: '悲觀的', explanation: 'Expecting bad things to happen.', examples: [{ sentence: 'Don\'t be so pessimistic.', translation: '不要那麼悲觀。' }], level: 'B1', tags: ['character', 'emotion'] },

  // ===== B2 - Law / Politics =====
  { word: 'democracy', pronunciation: '/dɪˈmɒkrəsi/', partOfSpeech: 'noun', translation: '民主', explanation: 'A system of government by the people.', examples: [{ sentence: 'Taiwan is a democracy.', translation: '台灣是民主國家。' }], level: 'B2', tags: ['politics', 'society'] },
  { word: 'election', pronunciation: '/ɪˈlɛkʃən/', partOfSpeech: 'noun', translation: '選舉', explanation: 'A process of choosing leaders by voting.', examples: [{ sentence: 'The election is next month.', translation: '選舉在下個月。' }], level: 'B2', tags: ['politics'] },
  { word: 'policy', pronunciation: '/ˈpɒlɪsi/', partOfSpeech: 'noun', translation: '政策', explanation: 'A plan or set of rules made by an organization.', examples: [{ sentence: 'The new policy is controversial.', translation: '新政策引起爭議。' }], level: 'B2', tags: ['politics', 'work'] },
  { word: 'constitution', pronunciation: '/ˌkɒnstɪˈtjuːʃən/', partOfSpeech: 'noun', translation: '憲法', explanation: 'The fundamental laws of a country.', examples: [{ sentence: 'The constitution protects citizens.', translation: '憲法保護公民。' }], level: 'B2', tags: ['politics', 'society'] },
  { word: 'justice', pronunciation: '/ˈdʒʌstɪs/', partOfSpeech: 'noun', translation: '正義；司法', explanation: 'Fair treatment according to the law.', examples: [{ sentence: 'We must fight for justice.', translation: '我們必須為正義而戰。' }], level: 'B2', tags: ['politics', 'society'] },
  { word: 'rights', pronunciation: '/raɪts/', partOfSpeech: 'noun', translation: '權利', explanation: 'Legal or moral entitlements.', examples: [{ sentence: 'Everyone has basic human rights.', translation: '每個人都有基本人權。' }], level: 'B2', tags: ['politics', 'society'] },
  { word: 'authority', pronunciation: '/ɔːˈθɒrɪti/', partOfSpeech: 'noun', translation: '當局；權威', explanation: 'The power to make decisions.', examples: [{ sentence: 'The authority approved the plan.', translation: '當局批准了計劃。' }], level: 'B2', tags: ['politics', 'society'] },
  { word: 'regulation', pronunciation: '/ˌrɛɡjʊˈleɪʃən/', partOfSpeech: 'noun', translation: '規定；法規', explanation: 'An official rule made by an authority.', examples: [{ sentence: 'New regulations were introduced.', translation: '引入了新規定。' }], level: 'B2', tags: ['politics', 'work'] },

  // ===== B2 - Science & Medicine =====
  { word: 'biology', pronunciation: '/baɪˈɒlədʒi/', partOfSpeech: 'noun', translation: '生物學', explanation: 'The study of living things.', examples: [{ sentence: 'She studies biology at university.', translation: '她在大學學習生物學。' }], level: 'B2', tags: ['science', 'education'] },
  { word: 'chemistry', pronunciation: '/ˈkɛmɪstri/', partOfSpeech: 'noun', translation: '化學', explanation: 'The study of the composition of matter.', examples: [{ sentence: 'Chemistry class is difficult.', translation: '化學課很難。' }], level: 'B2', tags: ['science', 'education'] },
  { word: 'physics', pronunciation: '/ˈfɪzɪks/', partOfSpeech: 'noun', translation: '物理學', explanation: 'The study of matter, energy and natural forces.', examples: [{ sentence: 'He is a physics professor.', translation: '他是一名物理學教授。' }], level: 'B2', tags: ['science', 'education'] },
  { word: 'experiment', pronunciation: '/ɪkˈspɛrɪmənt/', partOfSpeech: 'noun', translation: '實驗', explanation: 'A test done to discover or prove something.', examples: [{ sentence: 'The experiment was a success.', translation: '實驗成功了。' }], level: 'B2', tags: ['science'] },
  { word: 'theory', pronunciation: '/ˈθɪəri/', partOfSpeech: 'noun', translation: '理論', explanation: 'An idea to explain how something works.', examples: [{ sentence: 'Darwin\'s theory changed science.', translation: '達爾文的理論改變了科學。' }], level: 'B2', tags: ['science', 'academic'] },
  { word: 'surgery', pronunciation: '/ˈsɜːrdʒəri/', partOfSpeech: 'noun', translation: '外科手術', explanation: 'A medical operation on the body.', examples: [{ sentence: 'The surgery was successful.', translation: '手術很成功。' }], level: 'B2', tags: ['health', 'science'] },
  { word: 'diagnosis', pronunciation: '/ˌdaɪəɡˈnoʊsɪs/', partOfSpeech: 'noun', translation: '診斷', explanation: 'Identifying a disease or condition.', examples: [{ sentence: 'The diagnosis was cancer.', translation: '診斷結果是癌症。' }], level: 'B2', tags: ['health', 'science'] },
  { word: 'treatment', pronunciation: '/ˈtriːtmənt/', partOfSpeech: 'noun', translation: '治療', explanation: 'The process of curing an illness.', examples: [{ sentence: 'She is undergoing treatment.', translation: '她正在接受治療。' }], level: 'B2', tags: ['health'] },
  { word: 'vaccine', pronunciation: '/vækˈsiːn/', partOfSpeech: 'noun', translation: '疫苗', explanation: 'A substance given to prevent disease.', examples: [{ sentence: 'Get the vaccine to stay safe.', translation: '接種疫苗以保持安全。' }], level: 'B2', tags: ['health', 'science'] },
  { word: 'symptom', pronunciation: '/ˈsɪmptəm/', partOfSpeech: 'noun', translation: '症狀', explanation: 'A sign that indicates a disease.', examples: [{ sentence: 'What are your symptoms?', translation: '你有哪些症狀？' }], level: 'B2', tags: ['health'] },
];

async function run() {
  await mongoose.connect(MONGODB_URI, { serverSelectionTimeoutMS: 30000 });
  console.log('✅ MongoDB 連線成功');

  let added = 0, skipped = 0;
  for (const w of newWords) {
    const exists = await Vocabulary.findOne({ word: { $regex: `^${w.word}$`, $options: 'i' } });
    if (exists) { skipped++; continue; }
    await Vocabulary.create(w);
    added++;
  }

  const total = await Vocabulary.countDocuments();
  console.log(`✅ 新增 ${added} 個單字，跳過 ${skipped} 個重複`);
  console.log(`📚 資料庫現有 ${total} 個單字`);
  await mongoose.disconnect();
}

run().catch(err => { console.error(err); process.exit(1); });
