// 第二批次增量新增單字腳本 - 執行: node seed-batch2.js
require('dotenv').config();
const mongoose = require('mongoose');
const Vocabulary = require('./models/Vocabulary');

const MONGODB_URI = (process.env.MONGODB_URI || '').trim().replace(/ㄦ/g, '-');
if (!MONGODB_URI) { console.error('請設定 MONGODB_URI'); process.exit(1); }

const newWords = [
  // ===== A1 - Body Parts =====
  { word: 'head', pronunciation: '/hɛd/', partOfSpeech: 'noun', translation: '頭', explanation: 'The top part of the body.', examples: [{ sentence: 'She shook her head.', translation: '她搖了搖頭。' }], level: 'A1', tags: ['body'] },
  { word: 'face', pronunciation: '/feɪs/', partOfSpeech: 'noun', translation: '臉', explanation: 'The front part of the head.', examples: [{ sentence: 'Wash your face.', translation: '洗臉。' }], level: 'A1', tags: ['body'] },
  { word: 'eye', pronunciation: '/aɪ/', partOfSpeech: 'noun', translation: '眼睛', explanation: 'The organ of sight.', examples: [{ sentence: 'She has beautiful eyes.', translation: '她有漂亮的眼睛。' }], level: 'A1', tags: ['body'] },
  { word: 'ear', pronunciation: '/ɪr/', partOfSpeech: 'noun', translation: '耳朵', explanation: 'The organ of hearing.', examples: [{ sentence: 'The music hurts my ears.', translation: '這音樂傷我的耳朵。' }], level: 'A1', tags: ['body'] },
  { word: 'nose', pronunciation: '/noʊz/', partOfSpeech: 'noun', translation: '鼻子', explanation: 'The organ of smell.', examples: [{ sentence: 'My nose is runny.', translation: '我的鼻子流鼻水。' }], level: 'A1', tags: ['body'] },
  { word: 'mouth', pronunciation: '/maʊθ/', partOfSpeech: 'noun', translation: '嘴巴', explanation: 'The opening for eating and speaking.', examples: [{ sentence: 'Open your mouth.', translation: '張開嘴巴。' }], level: 'A1', tags: ['body'] },
  { word: 'tooth', pronunciation: '/tuːθ/', partOfSpeech: 'noun', translation: '牙齒', explanation: 'A hard white object in the mouth used for biting.', examples: [{ sentence: 'Brush your teeth.', translation: '刷牙。' }], level: 'A1', tags: ['body'] },
  { word: 'hair', pronunciation: '/hɛr/', partOfSpeech: 'noun', translation: '頭髮', explanation: 'The threads growing from the head.', examples: [{ sentence: 'She has long hair.', translation: '她有長頭髮。' }], level: 'A1', tags: ['body'] },
  { word: 'hand', pronunciation: '/hænd/', partOfSpeech: 'noun', translation: '手', explanation: 'The part at the end of the arm.', examples: [{ sentence: 'Raise your hand.', translation: '舉手。' }], level: 'A1', tags: ['body'] },
  { word: 'arm', pronunciation: '/ɑːrm/', partOfSpeech: 'noun', translation: '手臂', explanation: 'The upper limb of the body.', examples: [{ sentence: 'He broke his arm.', translation: '他摔斷了手臂。' }], level: 'A1', tags: ['body'] },
  { word: 'leg', pronunciation: '/lɛɡ/', partOfSpeech: 'noun', translation: '腿', explanation: 'The lower limb of the body.', examples: [{ sentence: 'My legs are tired.', translation: '我的腿很累。' }], level: 'A1', tags: ['body'] },
  { word: 'foot', pronunciation: '/fʊt/', partOfSpeech: 'noun', translation: '腳', explanation: 'The lower part of the leg.', examples: [{ sentence: 'My feet are sore.', translation: '我的腳很痠。' }], level: 'A1', tags: ['body'] },
  { word: 'back', pronunciation: '/bæk/', partOfSpeech: 'noun', translation: '背部', explanation: 'The rear part of the body.', examples: [{ sentence: 'I have a backache.', translation: '我背痛。' }], level: 'A1', tags: ['body'] },
  { word: 'shoulder', pronunciation: '/ˈʃoʊldər/', partOfSpeech: 'noun', translation: '肩膀', explanation: 'The joint between the arm and the body.', examples: [{ sentence: 'He tapped me on the shoulder.', translation: '他拍了拍我的肩膀。' }], level: 'A1', tags: ['body'] },
  { word: 'stomach', pronunciation: '/ˈstʌmək/', partOfSpeech: 'noun', translation: '胃；肚子', explanation: 'The organ that digests food; the abdomen.', examples: [{ sentence: 'My stomach is growling.', translation: '我的肚子在咕嚕叫。' }], level: 'A1', tags: ['body'] },

  // ===== A1 - House / Home =====
  { word: 'room', pronunciation: '/ruːm/', partOfSpeech: 'noun', translation: '房間', explanation: 'A space in a building.', examples: [{ sentence: 'Clean your room.', translation: '打掃你的房間。' }], level: 'A1', tags: ['home'] },
  { word: 'kitchen', pronunciation: '/ˈkɪtʃɪn/', partOfSpeech: 'noun', translation: '廚房', explanation: 'The room for cooking.', examples: [{ sentence: 'Mom is in the kitchen.', translation: '媽媽在廚房。' }], level: 'A1', tags: ['home'] },
  { word: 'bedroom', pronunciation: '/ˈbɛdruːm/', partOfSpeech: 'noun', translation: '臥室', explanation: 'A room for sleeping.', examples: [{ sentence: 'I share a bedroom with my sister.', translation: '我和姐姐共用一間臥室。' }], level: 'A1', tags: ['home'] },
  { word: 'bathroom', pronunciation: '/ˈbæθruːm/', partOfSpeech: 'noun', translation: '浴室', explanation: 'A room with a bath or shower.', examples: [{ sentence: 'The bathroom is upstairs.', translation: '浴室在樓上。' }], level: 'A1', tags: ['home'] },
  { word: 'garden', pronunciation: '/ˈɡɑːrdən/', partOfSpeech: 'noun', translation: '花園', explanation: 'An outdoor area for plants.', examples: [{ sentence: 'We grow vegetables in our garden.', translation: '我們在花園種蔬菜。' }], level: 'A1', tags: ['home'] },
  { word: 'door', pronunciation: '/dɔːr/', partOfSpeech: 'noun', translation: '門', explanation: 'A hinged barrier at the entrance of a room.', examples: [{ sentence: 'Please close the door.', translation: '請關門。' }], level: 'A1', tags: ['home'] },
  { word: 'window', pronunciation: '/ˈwɪndoʊ/', partOfSpeech: 'noun', translation: '窗戶', explanation: 'An opening in a wall for light and air.', examples: [{ sentence: 'Open the window please.', translation: '請開窗。' }], level: 'A1', tags: ['home'] },
  { word: 'floor', pronunciation: '/flɔːr/', partOfSpeech: 'noun', translation: '地板；樓層', explanation: 'The lower surface of a room.', examples: [{ sentence: 'Sit on the floor.', translation: '坐在地板上。' }], level: 'A1', tags: ['home'] },
  { word: 'wall', pronunciation: '/wɔːl/', partOfSpeech: 'noun', translation: '牆壁', explanation: 'A vertical structure that divides space.', examples: [{ sentence: 'The picture is on the wall.', translation: '圖片掛在牆上。' }], level: 'A1', tags: ['home'] },
  { word: 'stairs', pronunciation: '/stɛrz/', partOfSpeech: 'noun', translation: '樓梯', explanation: 'Steps leading from one floor to another.', examples: [{ sentence: 'Be careful on the stairs.', translation: '走樓梯要小心。' }], level: 'A1', tags: ['home'] },

  // ===== A1 - Food & Drinks =====
  { word: 'water', pronunciation: '/ˈwɔːtər/', partOfSpeech: 'noun', translation: '水', explanation: 'A clear liquid essential for life.', examples: [{ sentence: 'Drink more water every day.', translation: '每天多喝水。' }], level: 'A1', tags: ['food', 'drink'] },
  { word: 'milk', pronunciation: '/mɪlk/', partOfSpeech: 'noun', translation: '牛奶', explanation: 'A white liquid from cows.', examples: [{ sentence: 'I have milk for breakfast.', translation: '我早餐喝牛奶。' }], level: 'A1', tags: ['food', 'drink'] },
  { word: 'juice', pronunciation: '/dʒuːs/', partOfSpeech: 'noun', translation: '果汁', explanation: 'A liquid from fruit or vegetables.', examples: [{ sentence: 'I like orange juice.', translation: '我喜歡柳橙汁。' }], level: 'A1', tags: ['food', 'drink'] },
  { word: 'coffee', pronunciation: '/ˈkɒfi/', partOfSpeech: 'noun', translation: '咖啡', explanation: 'A hot drink made from roasted coffee beans.', examples: [{ sentence: 'He drinks coffee every morning.', translation: '他每天早上喝咖啡。' }], level: 'A1', tags: ['food', 'drink'] },
  { word: 'tea', pronunciation: '/tiː/', partOfSpeech: 'noun', translation: '茶', explanation: 'A hot drink made from tea leaves.', examples: [{ sentence: 'She prefers tea to coffee.', translation: '她比較喜歡茶而不是咖啡。' }], level: 'A1', tags: ['food', 'drink'] },
  { word: 'bread', pronunciation: '/brɛd/', partOfSpeech: 'noun', translation: '麵包', explanation: 'Food made from flour and baked.', examples: [{ sentence: 'I eat bread for breakfast.', translation: '我早餐吃麵包。' }], level: 'A1', tags: ['food'] },
  { word: 'rice', pronunciation: '/raɪs/', partOfSpeech: 'noun', translation: '米飯', explanation: 'Grains that are cooked and eaten.', examples: [{ sentence: 'We eat rice every day.', translation: '我們每天吃米飯。' }], level: 'A1', tags: ['food'] },
  { word: 'egg', pronunciation: '/ɛɡ/', partOfSpeech: 'noun', translation: '雞蛋', explanation: 'An oval object laid by a bird, often eaten.', examples: [{ sentence: 'I want two fried eggs.', translation: '我要兩個煎蛋。' }], level: 'A1', tags: ['food'] },
  { word: 'meat', pronunciation: '/miːt/', partOfSpeech: 'noun', translation: '肉', explanation: 'The flesh of an animal used as food.', examples: [{ sentence: 'I don\'t eat red meat.', translation: '我不吃紅肉。' }], level: 'A1', tags: ['food'] },
  { word: 'fish', pronunciation: '/fɪʃ/', partOfSpeech: 'noun', translation: '魚；魚肉', explanation: 'An aquatic animal; its flesh as food.', examples: [{ sentence: 'We had fish for dinner.', translation: '我們晚餐吃魚。' }], level: 'A1', tags: ['food', 'animal'] },
  { word: 'soup', pronunciation: '/suːp/', partOfSpeech: 'noun', translation: '湯', explanation: 'A liquid food made by boiling ingredients.', examples: [{ sentence: 'The soup is hot.', translation: '這湯很燙。' }], level: 'A1', tags: ['food'] },
  { word: 'salad', pronunciation: '/ˈsæləd/', partOfSpeech: 'noun', translation: '沙拉', explanation: 'A mix of raw vegetables.', examples: [{ sentence: 'I ordered a salad.', translation: '我點了一份沙拉。' }], level: 'A1', tags: ['food'] },
  { word: 'cake', pronunciation: '/keɪk/', partOfSpeech: 'noun', translation: '蛋糕', explanation: 'A sweet baked food.', examples: [{ sentence: 'Happy birthday! Here\'s your cake.', translation: '生日快樂！這是你的蛋糕。' }], level: 'A1', tags: ['food'] },
  { word: 'cookie', pronunciation: '/ˈkʊki/', partOfSpeech: 'noun', translation: '餅乾', explanation: 'A small, flat sweet biscuit.', examples: [{ sentence: 'She baked chocolate cookies.', translation: '她烤了巧克力餅乾。' }], level: 'A1', tags: ['food'] },
  { word: 'pizza', pronunciation: '/ˈpiːtsə/', partOfSpeech: 'noun', translation: '比薩', explanation: 'A flat bread topped with tomato and cheese.', examples: [{ sentence: 'Let\'s order pizza tonight.', translation: '今晚點比薩吧。' }], level: 'A1', tags: ['food'] },
  { word: 'sandwich', pronunciation: '/ˈsændwɪtʃ/', partOfSpeech: 'noun', translation: '三明治', explanation: 'Two slices of bread with filling.', examples: [{ sentence: 'I made a ham sandwich.', translation: '我做了一個火腿三明治。' }], level: 'A1', tags: ['food'] },
  { word: 'sugar', pronunciation: '/ˈʃʊɡər/', partOfSpeech: 'noun', translation: '糖', explanation: 'A sweet substance used in food.', examples: [{ sentence: 'Add sugar to your tea.', translation: '在茶裡加糖。' }], level: 'A1', tags: ['food'] },
  { word: 'salt', pronunciation: '/sɔːlt/', partOfSpeech: 'noun', translation: '鹽', explanation: 'A white mineral used to season food.', examples: [{ sentence: 'Pass the salt, please.', translation: '請把鹽遞給我。' }], level: 'A1', tags: ['food'] },

  // ===== A1 - Numbers / Quantity =====
  { word: 'hundred', pronunciation: '/ˈhʌndrəd/', partOfSpeech: 'number', translation: '一百', explanation: 'The number 100.', examples: [{ sentence: 'There are a hundred students.', translation: '有一百名學生。' }], level: 'A1', tags: ['number'] },
  { word: 'thousand', pronunciation: '/ˈθaʊzənd/', partOfSpeech: 'number', translation: '一千', explanation: 'The number 1000.', examples: [{ sentence: 'It costs a thousand dollars.', translation: '它花了一千美元。' }], level: 'A1', tags: ['number'] },
  { word: 'million', pronunciation: '/ˈmɪljən/', partOfSpeech: 'number', translation: '一百萬', explanation: 'The number 1,000,000.', examples: [{ sentence: 'The city has five million people.', translation: '這座城市有五百萬人。' }], level: 'A1', tags: ['number'] },
  { word: 'half', pronunciation: '/hæf/', partOfSpeech: 'noun', translation: '一半', explanation: 'One of two equal parts.', examples: [{ sentence: 'Give me half of your sandwich.', translation: '給我一半的三明治。' }], level: 'A1', tags: ['number'] },
  { word: 'quarter', pronunciation: '/ˈkwɔːrtər/', partOfSpeech: 'noun', translation: '四分之一', explanation: 'One of four equal parts.', examples: [{ sentence: 'A quarter of the class is absent.', translation: '四分之一的學生缺席。' }], level: 'A1', tags: ['number'] },

  // ===== A1 - Weather =====
  { word: 'weather', pronunciation: '/ˈwɛðər/', partOfSpeech: 'noun', translation: '天氣', explanation: 'The conditions outside.', examples: [{ sentence: 'The weather is nice today.', translation: '今天天氣很好。' }], level: 'A1', tags: ['weather'] },
  { word: 'sunny', pronunciation: '/ˈsʌni/', partOfSpeech: 'adjective', translation: '晴朗的', explanation: 'Bright with sunshine.', examples: [{ sentence: 'It\'s a sunny day.', translation: '今天是晴天。' }], level: 'A1', tags: ['weather'] },
  { word: 'cloudy', pronunciation: '/ˈklaʊdi/', partOfSpeech: 'adjective', translation: '多雲的', explanation: 'Covered with clouds.', examples: [{ sentence: 'It looks cloudy outside.', translation: '外面看起來多雲。' }], level: 'A1', tags: ['weather'] },
  { word: 'windy', pronunciation: '/ˈwɪndi/', partOfSpeech: 'adjective', translation: '有風的', explanation: 'With a lot of wind.', examples: [{ sentence: 'It\'s very windy today.', translation: '今天風很大。' }], level: 'A1', tags: ['weather'] },
  { word: 'rainy', pronunciation: '/ˈreɪni/', partOfSpeech: 'adjective', translation: '下雨的', explanation: 'Having a lot of rain.', examples: [{ sentence: 'Bring an umbrella on rainy days.', translation: '下雨天帶傘。' }], level: 'A1', tags: ['weather'] },
  { word: 'snowy', pronunciation: '/ˈsnoʊi/', partOfSpeech: 'adjective', translation: '下雪的', explanation: 'Having snow.', examples: [{ sentence: 'It\'s a snowy day.', translation: '今天是下雪天。' }], level: 'A1', tags: ['weather'] },
  { word: 'hot', pronunciation: '/hɒt/', partOfSpeech: 'adjective', translation: '熱的', explanation: 'Having a high temperature.', examples: [{ sentence: 'Summer is hot.', translation: '夏天很熱。' }], level: 'A1', tags: ['weather', 'temperature'] },
  { word: 'cold', pronunciation: '/koʊld/', partOfSpeech: 'adjective', translation: '冷的', explanation: 'Having a low temperature.', examples: [{ sentence: 'Winter is very cold.', translation: '冬天非常冷。' }], level: 'A1', tags: ['weather', 'temperature'] },
  { word: 'warm', pronunciation: '/wɔːrm/', partOfSpeech: 'adjective', translation: '溫暖的', explanation: 'Somewhat hot; comfortable in temperature.', examples: [{ sentence: 'Spring weather is warm.', translation: '春天的天氣很暖和。' }], level: 'A1', tags: ['weather', 'temperature'] },
  { word: 'cool', pronunciation: '/kuːl/', partOfSpeech: 'adjective', translation: '涼爽的', explanation: 'Fairly cold; pleasantly low temperature.', examples: [{ sentence: 'The evening is cool.', translation: '傍晚很涼爽。' }], level: 'A1', tags: ['weather', 'temperature'] },

  // ===== A2 - Travel & Transport =====
  { word: 'airport', pronunciation: '/ˈɛrpɔːrt/', partOfSpeech: 'noun', translation: '機場', explanation: 'A place where aircraft take off and land.', examples: [{ sentence: 'We arrived at the airport early.', translation: '我們很早到機場。' }], level: 'A2', tags: ['travel', 'transport'] },
  { word: 'station', pronunciation: '/ˈsteɪʃən/', partOfSpeech: 'noun', translation: '車站', explanation: 'A place where trains or buses stop.', examples: [{ sentence: 'Meet me at the train station.', translation: '在火車站和我碰面。' }], level: 'A2', tags: ['travel', 'transport'] },
  { word: 'ticket', pronunciation: '/ˈtɪkɪt/', partOfSpeech: 'noun', translation: '票', explanation: 'A piece of paper that shows you have paid.', examples: [{ sentence: 'I bought a return ticket.', translation: '我買了一張來回票。' }], level: 'A2', tags: ['travel'] },
  { word: 'passport', pronunciation: '/ˈpæspɔːrt/', partOfSpeech: 'noun', translation: '護照', explanation: 'An official document for international travel.', examples: [{ sentence: 'Don\'t forget your passport.', translation: '不要忘記護照。' }], level: 'A2', tags: ['travel', 'document'] },
  { word: 'luggage', pronunciation: '/ˈlʌɡɪdʒ/', partOfSpeech: 'noun', translation: '行李', explanation: 'Bags and suitcases for travel.', examples: [{ sentence: 'My luggage is too heavy.', translation: '我的行李太重了。' }], level: 'A2', tags: ['travel'] },
  { word: 'hotel', pronunciation: '/hoʊˈtɛl/', partOfSpeech: 'noun', translation: '飯店', explanation: 'A place to stay while travelling.', examples: [{ sentence: 'We stayed at a nice hotel.', translation: '我們住在一間不錯的飯店。' }], level: 'A2', tags: ['travel'] },
  { word: 'map', pronunciation: '/mæp/', partOfSpeech: 'noun', translation: '地圖', explanation: 'A diagram showing an area.', examples: [{ sentence: 'Can you read a map?', translation: '你會看地圖嗎？' }], level: 'A2', tags: ['travel'] },
  { word: 'tourist', pronunciation: '/ˈtʊərɪst/', partOfSpeech: 'noun', translation: '遊客', explanation: 'A person who visits a place for pleasure.', examples: [{ sentence: 'Many tourists visit the temple.', translation: '很多遊客參觀廟宇。' }], level: 'A2', tags: ['travel'] },
  { word: 'journey', pronunciation: '/ˈdʒɜːrni/', partOfSpeech: 'noun', translation: '旅途', explanation: 'A trip from one place to another.', examples: [{ sentence: 'The journey takes two hours.', translation: '旅途需要兩個小時。' }], level: 'A2', tags: ['travel'] },
  { word: 'destination', pronunciation: '/ˌdɛstɪˈneɪʃən/', partOfSpeech: 'noun', translation: '目的地', explanation: 'The place you are travelling to.', examples: [{ sentence: 'What is your final destination?', translation: '你的最終目的地是哪裡？' }], level: 'A2', tags: ['travel'] },
  { word: 'flight', pronunciation: '/flaɪt/', partOfSpeech: 'noun', translation: '航班', explanation: 'A journey by airplane.', examples: [{ sentence: 'The flight takes three hours.', translation: '這個航班需要三個小時。' }], level: 'A2', tags: ['travel', 'transport'] },
  { word: 'platform', pronunciation: '/ˈplætfɔːrm/', partOfSpeech: 'noun', translation: '月台', explanation: 'A raised area beside a railway track for passengers.', examples: [{ sentence: 'The train is at platform 3.', translation: '火車在第三月台。' }], level: 'A2', tags: ['travel', 'transport'] },

  // ===== A2 - Shopping =====
  { word: 'shop', pronunciation: '/ʃɒp/', partOfSpeech: 'noun', translation: '商店', explanation: 'A place where goods are sold.', examples: [{ sentence: 'There\'s a book shop nearby.', translation: '附近有一家書店。' }], level: 'A2', tags: ['shopping'] },
  { word: 'market', pronunciation: '/ˈmɑːrkɪt/', partOfSpeech: 'noun', translation: '市場', explanation: 'A place where goods are bought and sold.', examples: [{ sentence: 'We shop at the night market.', translation: '我們在夜市購物。' }], level: 'A2', tags: ['shopping'] },
  { word: 'price', pronunciation: '/praɪs/', partOfSpeech: 'noun', translation: '價格', explanation: 'The amount of money something costs.', examples: [{ sentence: 'What\'s the price of this?', translation: '這個多少錢？' }], level: 'A2', tags: ['shopping'] },
  { word: 'discount', pronunciation: '/ˈdɪskaʊnt/', partOfSpeech: 'noun', translation: '折扣', explanation: 'A reduction in price.', examples: [{ sentence: 'There\'s a 20% discount today.', translation: '今天有八折優惠。' }], level: 'A2', tags: ['shopping'] },
  { word: 'receipt', pronunciation: '/rɪˈsiːt/', partOfSpeech: 'noun', translation: '收據', explanation: 'A document showing payment has been made.', examples: [{ sentence: 'Keep your receipt.', translation: '保留你的收據。' }], level: 'A2', tags: ['shopping'] },
  { word: 'cash', pronunciation: '/kæʃ/', partOfSpeech: 'noun', translation: '現金', explanation: 'Money in the form of coins or notes.', examples: [{ sentence: 'Do you have cash?', translation: '你有現金嗎？' }], level: 'A2', tags: ['shopping', 'money'] },
  { word: 'credit card', pronunciation: '/ˈkrɛdɪt kɑːrd/', partOfSpeech: 'noun', translation: '信用卡', explanation: 'A card used to pay for things electronically.', examples: [{ sentence: 'Can I pay by credit card?', translation: '我可以用信用卡付款嗎？' }], level: 'A2', tags: ['shopping', 'money'] },
  { word: 'exchange', pronunciation: '/ɪksˈtʃeɪndʒ/', partOfSpeech: 'verb', translation: '交換；換匯', explanation: 'To swap one thing for another.', examples: [{ sentence: 'I want to exchange this for a larger size.', translation: '我想換一個大號的。' }], level: 'A2', tags: ['shopping'] },

  // ===== A2 - Health =====
  { word: 'hospital', pronunciation: '/ˈhɒspɪtəl/', partOfSpeech: 'noun', translation: '醫院', explanation: 'A place for treating sick people.', examples: [{ sentence: 'She works in a hospital.', translation: '她在醫院工作。' }], level: 'A2', tags: ['health'] },
  { word: 'doctor', pronunciation: '/ˈdɒktər/', partOfSpeech: 'noun', translation: '醫生', explanation: 'A person qualified to treat illnesses.', examples: [{ sentence: 'See a doctor if you feel ill.', translation: '感覺不舒服就去看醫生。' }], level: 'A2', tags: ['health', 'job'] },
  { word: 'nurse', pronunciation: '/nɜːrs/', partOfSpeech: 'noun', translation: '護士', explanation: 'A person trained to care for patients.', examples: [{ sentence: 'The nurse checked my blood pressure.', translation: '護士量了我的血壓。' }], level: 'A2', tags: ['health', 'job'] },
  { word: 'medicine', pronunciation: '/ˈmɛdɪsɪn/', partOfSpeech: 'noun', translation: '藥；醫學', explanation: 'A substance used to treat illness.', examples: [{ sentence: 'Take this medicine twice a day.', translation: '這藥一天服用兩次。' }], level: 'A2', tags: ['health'] },
  { word: 'sick', pronunciation: '/sɪk/', partOfSpeech: 'adjective', translation: '生病的', explanation: 'Not in good health; ill.', examples: [{ sentence: 'I stayed home because I was sick.', translation: '我因為生病待在家。' }], level: 'A2', tags: ['health'] },
  { word: 'pain', pronunciation: '/peɪn/', partOfSpeech: 'noun', translation: '疼痛', explanation: 'An unpleasant feeling in part of the body.', examples: [{ sentence: 'I feel a sharp pain in my knee.', translation: '我膝蓋感到劇烈疼痛。' }], level: 'A2', tags: ['health'] },
  { word: 'fever', pronunciation: '/ˈfiːvər/', partOfSpeech: 'noun', translation: '發燒', explanation: 'A high body temperature caused by illness.', examples: [{ sentence: 'She has a high fever.', translation: '她發高燒。' }], level: 'A2', tags: ['health'] },
  { word: 'cough', pronunciation: '/kɒf/', partOfSpeech: 'noun', translation: '咳嗽', explanation: 'A sudden loud noise from the throat.', examples: [{ sentence: 'I have a bad cough.', translation: '我咳嗽很嚴重。' }], level: 'A2', tags: ['health'] },
  { word: 'headache', pronunciation: '/ˈhɛdeɪk/', partOfSpeech: 'noun', translation: '頭痛', explanation: 'A continuous pain in the head.', examples: [{ sentence: 'I have a terrible headache.', translation: '我頭很痛。' }], level: 'A2', tags: ['health'] },
  { word: 'allergy', pronunciation: '/ˈælərdʒi/', partOfSpeech: 'noun', translation: '過敏', explanation: 'A bad reaction to a substance.', examples: [{ sentence: 'I have an allergy to pollen.', translation: '我對花粉過敏。' }], level: 'A2', tags: ['health'] },
  { word: 'exercise', pronunciation: '/ˈɛksərsaɪz/', partOfSpeech: 'noun', translation: '運動', explanation: 'Physical activity to keep fit.', examples: [{ sentence: 'Regular exercise is good for health.', translation: '規律運動對健康有益。' }], level: 'A2', tags: ['health', 'sport'] },

  // ===== A2 - Jobs / Work =====
  { word: 'job', pronunciation: '/dʒɒb/', partOfSpeech: 'noun', translation: '工作', explanation: 'Regular paid employment.', examples: [{ sentence: 'She has a great job.', translation: '她有一份好工作。' }], level: 'A2', tags: ['work'] },
  { word: 'office', pronunciation: '/ˈɒfɪs/', partOfSpeech: 'noun', translation: '辦公室', explanation: 'A room or building for work.', examples: [{ sentence: 'I work in a small office.', translation: '我在一間小辦公室工作。' }], level: 'A2', tags: ['work'] },
  { word: 'salary', pronunciation: '/ˈsæləri/', partOfSpeech: 'noun', translation: '薪水', explanation: 'Regular pay for work.', examples: [{ sentence: 'His salary is quite high.', translation: '他的薪水相當高。' }], level: 'A2', tags: ['work', 'money'] },
  { word: 'boss', pronunciation: '/bɒs/', partOfSpeech: 'noun', translation: '老闆', explanation: 'The manager or employer.', examples: [{ sentence: 'My boss is very strict.', translation: '我老闆非常嚴格。' }], level: 'A2', tags: ['work'] },
  { word: 'colleague', pronunciation: '/ˈkɒliːɡ/', partOfSpeech: 'noun', translation: '同事', explanation: 'A person you work with.', examples: [{ sentence: 'My colleagues are friendly.', translation: '我的同事很友善。' }], level: 'A2', tags: ['work'] },
  { word: 'meeting', pronunciation: '/ˈmiːtɪŋ/', partOfSpeech: 'noun', translation: '會議', explanation: 'A gathering of people to discuss something.', examples: [{ sentence: 'I have a meeting at 2 pm.', translation: '我下午兩點有會議。' }], level: 'A2', tags: ['work'] },
  { word: 'engineer', pronunciation: '/ˌɛndʒɪˈnɪər/', partOfSpeech: 'noun', translation: '工程師', explanation: 'A person who designs or builds machines.', examples: [{ sentence: 'He is a software engineer.', translation: '他是一名軟體工程師。' }], level: 'A2', tags: ['work', 'job'] },
  { word: 'teacher', pronunciation: '/ˈtiːtʃər/', partOfSpeech: 'noun', translation: '老師', explanation: 'A person who teaches others.', examples: [{ sentence: 'She is a great teacher.', translation: '她是一位很棒的老師。' }], level: 'A2', tags: ['work', 'job', 'education'] },
  { word: 'driver', pronunciation: '/ˈdraɪvər/', partOfSpeech: 'noun', translation: '司機', explanation: 'A person who drives a vehicle.', examples: [{ sentence: 'The taxi driver was very polite.', translation: '計程車司機很有禮貌。' }], level: 'A2', tags: ['work', 'job'] },
  { word: 'chef', pronunciation: '/ʃɛf/', partOfSpeech: 'noun', translation: '廚師', explanation: 'A professional cook.', examples: [{ sentence: 'The chef prepared a delicious meal.', translation: '廚師準備了一頓美味的餐點。' }], level: 'A2', tags: ['work', 'job', 'food'] },
  { word: 'lawyer', pronunciation: '/ˈlɔːjər/', partOfSpeech: 'noun', translation: '律師', explanation: 'A person who practises law.', examples: [{ sentence: 'I need to speak to a lawyer.', translation: '我需要找律師談談。' }], level: 'A2', tags: ['work', 'job'] },
  { word: 'police', pronunciation: '/pəˈliːs/', partOfSpeech: 'noun', translation: '警察', explanation: 'Officers who enforce the law.', examples: [{ sentence: 'Call the police!', translation: '叫警察！' }], level: 'A2', tags: ['work', 'job'] },

  // ===== B1 - Communication =====
  { word: 'conversation', pronunciation: '/ˌkɒnvərˈseɪʃən/', partOfSpeech: 'noun', translation: '對話；會談', explanation: 'An informal spoken exchange.', examples: [{ sentence: 'We had a long conversation.', translation: '我們進行了一場長談。' }], level: 'B1', tags: ['communication'] },
  { word: 'discuss', pronunciation: '/dɪˈskʌs/', partOfSpeech: 'verb', translation: '討論', explanation: 'To talk about something in detail.', examples: [{ sentence: 'Let\'s discuss this problem.', translation: '讓我們討論這個問題。' }], level: 'B1', tags: ['communication'] },
  { word: 'argue', pronunciation: '/ˈɑːrɡjuː/', partOfSpeech: 'verb', translation: '爭論', explanation: 'To disagree with someone angrily.', examples: [{ sentence: 'They always argue about money.', translation: '他們總是為錢吵架。' }], level: 'B1', tags: ['communication'] },
  { word: 'agree', pronunciation: '/əˈɡriː/', partOfSpeech: 'verb', translation: '同意', explanation: 'To have the same opinion.', examples: [{ sentence: 'I agree with your idea.', translation: '我同意你的想法。' }], level: 'B1', tags: ['communication'] },
  { word: 'disagree', pronunciation: '/ˌdɪsəˈɡriː/', partOfSpeech: 'verb', translation: '不同意', explanation: 'To have a different opinion.', examples: [{ sentence: 'I disagree with that statement.', translation: '我不同意那個說法。' }], level: 'B1', tags: ['communication'] },
  { word: 'opinion', pronunciation: '/əˈpɪnjən/', partOfSpeech: 'noun', translation: '意見；看法', explanation: 'A personal view or judgement.', examples: [{ sentence: 'In my opinion, this is wrong.', translation: '在我看來，這是錯誤的。' }], level: 'B1', tags: ['communication'] },
  { word: 'suggest', pronunciation: '/səˈdʒɛst/', partOfSpeech: 'verb', translation: '建議', explanation: 'To put forward an idea for consideration.', examples: [{ sentence: 'I suggest we leave early.', translation: '我建議我們早點離開。' }], level: 'B1', tags: ['communication'] },
  { word: 'recommend', pronunciation: '/ˌrɛkəˈmɛnd/', partOfSpeech: 'verb', translation: '推薦', explanation: 'To suggest something as good.', examples: [{ sentence: 'Can you recommend a good book?', translation: '你能推薦一本好書嗎？' }], level: 'B1', tags: ['communication'] },
  { word: 'complain', pronunciation: '/kəmˈpleɪn/', partOfSpeech: 'verb', translation: '抱怨', explanation: 'To express dissatisfaction.', examples: [{ sentence: 'She always complains about the food.', translation: '她總是抱怨食物。' }], level: 'B1', tags: ['communication'] },
  { word: 'apologize', pronunciation: '/əˈpɒlədʒaɪz/', partOfSpeech: 'verb', translation: '道歉', explanation: 'To express regret for a mistake.', examples: [{ sentence: 'I apologize for being late.', translation: '我為遲到道歉。' }], level: 'B1', tags: ['communication'] },

  // ===== B1 - Feelings & Emotions =====
  { word: 'anxious', pronunciation: '/ˈæŋkʃəs/', partOfSpeech: 'adjective', translation: '焦慮的', explanation: 'Feeling worried or nervous.', examples: [{ sentence: 'She felt anxious before the exam.', translation: '她在考試前感到焦慮。' }], level: 'B1', tags: ['emotion'] },
  { word: 'confident', pronunciation: '/ˈkɒnfɪdənt/', partOfSpeech: 'adjective', translation: '自信的', explanation: 'Feeling sure about oneself.', examples: [{ sentence: 'He gave a confident speech.', translation: '他做了一個自信的演講。' }], level: 'B1', tags: ['emotion', 'character'] },
  { word: 'curious', pronunciation: '/ˈkjʊəriəs/', partOfSpeech: 'adjective', translation: '好奇的', explanation: 'Eager to learn or know something.', examples: [{ sentence: 'Children are naturally curious.', translation: '孩子天生好奇。' }], level: 'B1', tags: ['emotion', 'character'] },
  { word: 'frustrated', pronunciation: '/frʌˈstreɪtɪd/', partOfSpeech: 'adjective', translation: '沮喪的；挫折的', explanation: 'Feeling annoyed because of obstacles.', examples: [{ sentence: 'He felt frustrated with the slow progress.', translation: '他對緩慢的進展感到沮喪。' }], level: 'B1', tags: ['emotion'] },
  { word: 'proud', pronunciation: '/praʊd/', partOfSpeech: 'adjective', translation: '驕傲的', explanation: 'Feeling pleased with achievements.', examples: [{ sentence: 'Her parents are very proud of her.', translation: '她的父母非常以她為傲。' }], level: 'B1', tags: ['emotion'] },
  { word: 'jealous', pronunciation: '/ˈdʒɛləs/', partOfSpeech: 'adjective', translation: '嫉妒的', explanation: 'Feeling envious of someone.', examples: [{ sentence: 'He was jealous of her success.', translation: '他嫉妒她的成功。' }], level: 'B1', tags: ['emotion'] },
  { word: 'lonely', pronunciation: '/ˈloʊnli/', partOfSpeech: 'adjective', translation: '孤獨的', explanation: 'Feeling sad because of lack of company.', examples: [{ sentence: 'She felt lonely in the new city.', translation: '她在新城市感到孤獨。' }], level: 'B1', tags: ['emotion'] },
  { word: 'embarrassed', pronunciation: '/ɪmˈbærəst/', partOfSpeech: 'adjective', translation: '尷尬的', explanation: 'Feeling self-conscious or ashamed.', examples: [{ sentence: 'I was embarrassed by my mistake.', translation: '我為自己的錯誤感到尷尬。' }], level: 'B1', tags: ['emotion'] },
  { word: 'grateful', pronunciation: '/ˈɡreɪtfəl/', partOfSpeech: 'adjective', translation: '感激的', explanation: 'Feeling thankful for something received.', examples: [{ sentence: 'I am grateful for your help.', translation: '我很感激你的幫助。' }], level: 'B1', tags: ['emotion'] },
  { word: 'relieved', pronunciation: '/rɪˈliːvd/', partOfSpeech: 'adjective', translation: '放心的', explanation: 'Feeling that worry has been removed.', examples: [{ sentence: 'I was relieved to hear the news.', translation: '我聽到這個消息感到鬆了一口氣。' }], level: 'B1', tags: ['emotion'] },

  // ===== B1 - Education =====
  { word: 'university', pronunciation: '/ˌjuːnɪˈvɜːrsɪti/', partOfSpeech: 'noun', translation: '大學', explanation: 'A higher education institution.', examples: [{ sentence: 'She studies at a top university.', translation: '她在頂尖大學就讀。' }], level: 'B1', tags: ['education'] },
  { word: 'degree', pronunciation: '/dɪˈɡriː/', partOfSpeech: 'noun', translation: '學位', explanation: 'An academic qualification.', examples: [{ sentence: 'He has a degree in engineering.', translation: '他有工程學學位。' }], level: 'B1', tags: ['education'] },
  { word: 'graduate', pronunciation: '/ˈɡrædʒuɪt/', partOfSpeech: 'verb', translation: '畢業', explanation: 'To complete a course of study.', examples: [{ sentence: 'She graduated last year.', translation: '她去年畢業了。' }], level: 'B1', tags: ['education'] },
  { word: 'research', pronunciation: '/rɪˈsɜːrtʃ/', partOfSpeech: 'noun', translation: '研究', explanation: 'Careful study to find new information.', examples: [{ sentence: 'He does research in genetics.', translation: '他從事遺傳學研究。' }], level: 'B1', tags: ['education', 'science'] },
  { word: 'essay', pronunciation: '/ˈɛseɪ/', partOfSpeech: 'noun', translation: '短文；論文', explanation: 'A short piece of writing on a topic.', examples: [{ sentence: 'Write a 500-word essay.', translation: '寫一篇500字的短文。' }], level: 'B1', tags: ['education', 'writing'] },
  { word: 'assignment', pronunciation: '/əˈsaɪnmənt/', partOfSpeech: 'noun', translation: '作業；任務', explanation: 'A piece of work given by a teacher.', examples: [{ sentence: 'I haven\'t finished my assignment.', translation: '我還沒完成作業。' }], level: 'B1', tags: ['education'] },
  { word: 'lecture', pronunciation: '/ˈlɛktʃər/', partOfSpeech: 'noun', translation: '講座；課堂', explanation: 'A talk given to a class or audience.', examples: [{ sentence: 'The lecture was very interesting.', translation: '這堂課非常有趣。' }], level: 'B1', tags: ['education'] },
  { word: 'scholarship', pronunciation: '/ˈskɒlərʃɪp/', partOfSpeech: 'noun', translation: '獎學金', explanation: 'Financial help given to a student.', examples: [{ sentence: 'She won a scholarship.', translation: '她獲得了獎學金。' }], level: 'B1', tags: ['education'] },

  // ===== B1 - Technology =====
  { word: 'device', pronunciation: '/dɪˈvaɪs/', partOfSpeech: 'noun', translation: '裝置；設備', explanation: 'A machine or tool for a specific purpose.', examples: [{ sentence: 'This device is very useful.', translation: '這個設備非常有用。' }], level: 'B1', tags: ['technology'] },
  { word: 'software', pronunciation: '/ˈsɒftweər/', partOfSpeech: 'noun', translation: '軟體', explanation: 'Programs used by a computer.', examples: [{ sentence: 'Update your software regularly.', translation: '定期更新軟體。' }], level: 'B1', tags: ['technology'] },
  { word: 'download', pronunciation: '/ˈdaʊnloʊd/', partOfSpeech: 'verb', translation: '下載', explanation: 'To copy data from the internet to a device.', examples: [{ sentence: 'Download the app for free.', translation: '免費下載這個應用程式。' }], level: 'B1', tags: ['technology'] },
  { word: 'upload', pronunciation: '/ˈʌploʊd/', partOfSpeech: 'verb', translation: '上傳', explanation: 'To transfer data from a device to the internet.', examples: [{ sentence: 'Upload your photo here.', translation: '在這裡上傳你的照片。' }], level: 'B1', tags: ['technology'] },
  { word: 'password', pronunciation: '/ˈpæswɜːrd/', partOfSpeech: 'noun', translation: '密碼', explanation: 'A secret word used to access a system.', examples: [{ sentence: 'Create a strong password.', translation: '建立一個強密碼。' }], level: 'B1', tags: ['technology'] },
  { word: 'network', pronunciation: '/ˈnɛtwɜːrk/', partOfSpeech: 'noun', translation: '網路；網絡', explanation: 'A system of connected computers or people.', examples: [{ sentence: 'The network is down.', translation: '網路中斷了。' }], level: 'B1', tags: ['technology'] },
  { word: 'application', pronunciation: '/ˌæplɪˈkeɪʃən/', partOfSpeech: 'noun', translation: '應用程式；申請', explanation: 'A computer program for a specific use.', examples: [{ sentence: 'This application is very popular.', translation: '這個應用程式非常受歡迎。' }], level: 'B1', tags: ['technology'] },
  { word: 'digital', pronunciation: '/ˈdɪdʒɪtəl/', partOfSpeech: 'adjective', translation: '數位的', explanation: 'Relating to computer technology.', examples: [{ sentence: 'We live in a digital world.', translation: '我們生活在數位世界。' }], level: 'B1', tags: ['technology'] },
  { word: 'wireless', pronunciation: '/ˈwaɪərləs/', partOfSpeech: 'adjective', translation: '無線的', explanation: 'Using radio signals instead of wires.', examples: [{ sentence: 'Is there wireless internet here?', translation: '這裡有無線網路嗎？' }], level: 'B1', tags: ['technology'] },

  // ===== B1 - Society & Environment =====
  { word: 'pollution', pronunciation: '/pəˈluːʃən/', partOfSpeech: 'noun', translation: '污染', explanation: 'Harmful substances in the environment.', examples: [{ sentence: 'Air pollution is a serious problem.', translation: '空氣污染是一個嚴重問題。' }], level: 'B1', tags: ['environment'] },
  { word: 'recycle', pronunciation: '/ˌriːˈsaɪkəl/', partOfSpeech: 'verb', translation: '回收', explanation: 'To process waste for reuse.', examples: [{ sentence: 'Please recycle your bottles.', translation: '請回收你的瓶子。' }], level: 'B1', tags: ['environment'] },
  { word: 'climate', pronunciation: '/ˈklaɪmɪt/', partOfSpeech: 'noun', translation: '氣候', explanation: 'The typical weather in an area over time.', examples: [{ sentence: 'The climate is changing rapidly.', translation: '氣候正在迅速變化。' }], level: 'B1', tags: ['environment', 'weather'] },
  { word: 'energy', pronunciation: '/ˈɛnərdʒi/', partOfSpeech: 'noun', translation: '能源；精力', explanation: 'Power from fuel; capacity to do work.', examples: [{ sentence: 'We need renewable energy.', translation: '我們需要可再生能源。' }], level: 'B1', tags: ['environment', 'science'] },
  { word: 'resource', pronunciation: '/ˈriːsɔːrs/', partOfSpeech: 'noun', translation: '資源', explanation: 'A supply of something useful.', examples: [{ sentence: 'Water is a precious resource.', translation: '水是珍貴的資源。' }], level: 'B1', tags: ['environment'] },
  { word: 'society', pronunciation: '/səˈsaɪɪti/', partOfSpeech: 'noun', translation: '社會', explanation: 'A community of people with shared laws.', examples: [{ sentence: 'Technology shapes modern society.', translation: '科技塑造了現代社會。' }], level: 'B1', tags: ['society'] },
  { word: 'culture', pronunciation: '/ˈkʌltʃər/', partOfSpeech: 'noun', translation: '文化', explanation: 'The customs and arts of a society.', examples: [{ sentence: 'Taiwan has a rich culture.', translation: '台灣有豐富的文化。' }], level: 'B1', tags: ['society'] },
  { word: 'tradition', pronunciation: '/trəˈdɪʃən/', partOfSpeech: 'noun', translation: '傳統', explanation: 'A belief or custom passed down through generations.', examples: [{ sentence: 'We follow family traditions.', translation: '我們遵循家庭傳統。' }], level: 'B1', tags: ['society'] },
  { word: 'government', pronunciation: '/ˈɡʌvərnmənt/', partOfSpeech: 'noun', translation: '政府', explanation: 'The group that controls a country.', examples: [{ sentence: 'The government announced new policies.', translation: '政府宣布了新政策。' }], level: 'B1', tags: ['society', 'politics'] },
  { word: 'law', pronunciation: '/lɔː/', partOfSpeech: 'noun', translation: '法律', explanation: 'A rule made by the government.', examples: [{ sentence: 'Everyone must follow the law.', translation: '每個人都必須遵守法律。' }], level: 'B1', tags: ['society', 'politics'] },

  // ===== B2 - Abstract / Academic =====
  { word: 'phenomenon', pronunciation: '/fɪˈnɒmɪnɒn/', partOfSpeech: 'noun', translation: '現象', explanation: 'An observable fact or event.', examples: [{ sentence: 'Globalization is a complex phenomenon.', translation: '全球化是一個複雜的現象。' }], level: 'B2', tags: ['academic'] },
  { word: 'perspective', pronunciation: '/pərˈspɛktɪv/', partOfSpeech: 'noun', translation: '觀點；角度', explanation: 'A particular way of thinking about something.', examples: [{ sentence: 'Consider it from a different perspective.', translation: '從不同角度考慮它。' }], level: 'B2', tags: ['academic'] },
  { word: 'hypothesis', pronunciation: '/haɪˈpɒθɪsɪs/', partOfSpeech: 'noun', translation: '假說；假設', explanation: 'An idea that needs to be tested.', examples: [{ sentence: 'The hypothesis was proven wrong.', translation: '這個假說被證明是錯的。' }], level: 'B2', tags: ['academic', 'science'] },
  { word: 'analysis', pronunciation: '/əˈnælɪsɪs/', partOfSpeech: 'noun', translation: '分析', explanation: 'A detailed examination of something.', examples: [{ sentence: 'The analysis shows interesting results.', translation: '分析顯示了有趣的結果。' }], level: 'B2', tags: ['academic'] },
  { word: 'concept', pronunciation: '/ˈkɒnsɛpt/', partOfSpeech: 'noun', translation: '概念', explanation: 'An abstract idea or general notion.', examples: [{ sentence: 'This is a difficult concept to grasp.', translation: '這是一個難以理解的概念。' }], level: 'B2', tags: ['academic'] },
  { word: 'evaluate', pronunciation: '/ɪˈvæljueɪt/', partOfSpeech: 'verb', translation: '評估', explanation: 'To judge the quality or value of something.', examples: [{ sentence: 'We need to evaluate the results.', translation: '我們需要評估結果。' }], level: 'B2', tags: ['academic'] },
  { word: 'implement', pronunciation: '/ˈɪmplɪmɛnt/', partOfSpeech: 'verb', translation: '實施；執行', explanation: 'To put a plan into action.', examples: [{ sentence: 'The company will implement the new policy.', translation: '公司將實施新政策。' }], level: 'B2', tags: ['academic', 'work'] },
  { word: 'consistent', pronunciation: '/kənˈsɪstənt/', partOfSpeech: 'adjective', translation: '一致的', explanation: 'Always the same; not changing.', examples: [{ sentence: 'Her performance is consistent.', translation: '她的表現很穩定。' }], level: 'B2', tags: ['academic'] },
  { word: 'contrast', pronunciation: '/ˈkɒntrɑːst/', partOfSpeech: 'noun', translation: '對比；差異', explanation: 'A difference between two things.', examples: [{ sentence: 'There\'s a strong contrast between them.', translation: '他們之間有很大的對比。' }], level: 'B2', tags: ['academic'] },
  { word: 'imply', pronunciation: '/ɪmˈplaɪ/', partOfSpeech: 'verb', translation: '暗示', explanation: 'To suggest something without saying it.', examples: [{ sentence: 'What does this result imply?', translation: '這個結果暗示了什麼？' }], level: 'B2', tags: ['academic', 'communication'] },
  { word: 'assume', pronunciation: '/əˈsjuːm/', partOfSpeech: 'verb', translation: '假設；認為', explanation: 'To suppose something without proof.', examples: [{ sentence: 'Don\'t assume the worst.', translation: '不要總往最壞的方向想。' }], level: 'B2', tags: ['academic'] },
  { word: 'highlight', pronunciation: '/ˈhaɪlaɪt/', partOfSpeech: 'verb', translation: '強調；突出', explanation: 'To draw attention to something.', examples: [{ sentence: 'The report highlights key issues.', translation: '報告強調了關鍵問題。' }], level: 'B2', tags: ['academic', 'communication'] },
  { word: 'elaborate', pronunciation: '/ɪˈlæbərɪt/', partOfSpeech: 'verb', translation: '詳細說明', explanation: 'To give more details about something.', examples: [{ sentence: 'Can you elaborate on that point?', translation: '你能詳細說明那一點嗎？' }], level: 'B2', tags: ['academic', 'communication'] },
  { word: 'inevitable', pronunciation: '/ɪnˈɛvɪtəbəl/', partOfSpeech: 'adjective', translation: '不可避免的', explanation: 'Certain to happen and impossible to avoid.', examples: [{ sentence: 'Change is inevitable.', translation: '變化是不可避免的。' }], level: 'B2', tags: ['academic'] },
  { word: 'crucial', pronunciation: '/ˈkruːʃəl/', partOfSpeech: 'adjective', translation: '關鍵的', explanation: 'Extremely important.', examples: [{ sentence: 'This decision is crucial.', translation: '這個決定至關重要。' }], level: 'B2', tags: ['academic'] },
  { word: 'sustainable', pronunciation: '/səˈsteɪnəbəl/', partOfSpeech: 'adjective', translation: '可持續的', explanation: 'Able to be maintained without harming the environment.', examples: [{ sentence: 'We need sustainable energy solutions.', translation: '我們需要可持續的能源解決方案。' }], level: 'B2', tags: ['environment', 'academic'] },
  { word: 'infrastructure', pronunciation: '/ˈɪnfrəstrʌktʃər/', partOfSpeech: 'noun', translation: '基礎設施', explanation: 'The basic systems of a country.', examples: [{ sentence: 'The city needs better infrastructure.', translation: '這座城市需要更好的基礎設施。' }], level: 'B2', tags: ['society', 'academic'] },
  { word: 'diversity', pronunciation: '/daɪˈvɜːrsɪti/', partOfSpeech: 'noun', translation: '多樣性', explanation: 'A range of different things or people.', examples: [{ sentence: 'The team celebrates diversity.', translation: '這個團隊慶祝多樣性。' }], level: 'B2', tags: ['society', 'academic'] },
  { word: 'innovation', pronunciation: '/ˌɪnəˈveɪʃən/', partOfSpeech: 'noun', translation: '創新', explanation: 'A new idea or method.', examples: [{ sentence: 'Innovation drives economic growth.', translation: '創新推動經濟增長。' }], level: 'B2', tags: ['work', 'academic'] },
  { word: 'controversy', pronunciation: '/ˈkɒntrəvɜːrsi/', partOfSpeech: 'noun', translation: '爭議', explanation: 'Disagreement or debate about something.', examples: [{ sentence: 'The topic caused much controversy.', translation: '這個話題引起了很大爭議。' }], level: 'B2', tags: ['society', 'academic'] },
  { word: 'outcome', pronunciation: '/ˈaʊtkʌm/', partOfSpeech: 'noun', translation: '結果；成果', explanation: 'The final result of something.', examples: [{ sentence: 'The outcome was better than expected.', translation: '結果比預期更好。' }], level: 'B2', tags: ['academic'] },
  { word: 'derive', pronunciation: '/dɪˈraɪv/', partOfSpeech: 'verb', translation: '衍生；獲得', explanation: 'To obtain something from a source.', examples: [{ sentence: 'Many words derive from Latin.', translation: '許多單字源自拉丁語。' }], level: 'B2', tags: ['academic', 'language'] },
  { word: 'interpret', pronunciation: '/ɪnˈtɜːrprɪt/', partOfSpeech: 'verb', translation: '解釋；詮釋', explanation: 'To explain the meaning of something.', examples: [{ sentence: 'How do you interpret this poem?', translation: '你如何詮釋這首詩？' }], level: 'B2', tags: ['academic', 'language'] },
  { word: 'justify', pronunciation: '/ˈdʒʌstɪfaɪ/', partOfSpeech: 'verb', translation: '證明正當；辯護', explanation: 'To show that something is right or necessary.', examples: [{ sentence: 'Can you justify your decision?', translation: '你能為你的決定辯護嗎？' }], level: 'B2', tags: ['academic'] },
  { word: 'acknowledge', pronunciation: '/ækˈnɒlɪdʒ/', partOfSpeech: 'verb', translation: '承認；致謝', explanation: 'To admit the truth of something.', examples: [{ sentence: 'He acknowledged his mistake.', translation: '他承認了自己的錯誤。' }], level: 'B2', tags: ['academic', 'communication'] },

  // ===== B2 - Economy & Business =====
  { word: 'economy', pronunciation: '/ɪˈkɒnəmi/', partOfSpeech: 'noun', translation: '經濟', explanation: 'The financial system of a country.', examples: [{ sentence: 'The economy is growing steadily.', translation: '經濟正穩步增長。' }], level: 'B2', tags: ['economy'] },
  { word: 'investment', pronunciation: '/ɪnˈvɛstmənt/', partOfSpeech: 'noun', translation: '投資', explanation: 'Money put into something to gain profit.', examples: [{ sentence: 'This is a wise investment.', translation: '這是明智的投資。' }], level: 'B2', tags: ['economy', 'money'] },
  { word: 'profit', pronunciation: '/ˈprɒfɪt/', partOfSpeech: 'noun', translation: '利潤', explanation: 'The money earned after expenses.', examples: [{ sentence: 'The company made a large profit.', translation: '公司賺了大量利潤。' }], level: 'B2', tags: ['economy', 'work'] },
  { word: 'debt', pronunciation: '/dɛt/', partOfSpeech: 'noun', translation: '債務', explanation: 'Money owed to someone else.', examples: [{ sentence: 'He is in serious debt.', translation: '他負有嚴重債務。' }], level: 'B2', tags: ['economy', 'money'] },
  { word: 'budget', pronunciation: '/ˈbʌdʒɪt/', partOfSpeech: 'noun', translation: '預算', explanation: 'A plan for spending money.', examples: [{ sentence: 'We need to stick to the budget.', translation: '我們需要遵守預算。' }], level: 'B2', tags: ['economy', 'money'] },
  { word: 'contract', pronunciation: '/ˈkɒntrækt/', partOfSpeech: 'noun', translation: '合約', explanation: 'A legal written agreement.', examples: [{ sentence: 'Sign the contract before you start.', translation: '開始之前先簽合約。' }], level: 'B2', tags: ['work', 'economy'] },
  { word: 'negotiate', pronunciation: '/nɪˈɡoʊʃieɪt/', partOfSpeech: 'verb', translation: '談判；協商', explanation: 'To reach an agreement through discussion.', examples: [{ sentence: 'They negotiated a better deal.', translation: '他們談判達成了更好的交易。' }], level: 'B2', tags: ['work', 'communication'] },
  { word: 'competitive', pronunciation: '/kəmˈpɛtɪtɪv/', partOfSpeech: 'adjective', translation: '競爭的；有競爭力的', explanation: 'Relating to or determined by competition.', examples: [{ sentence: 'The market is very competitive.', translation: '市場競爭非常激烈。' }], level: 'B2', tags: ['work', 'economy'] },
];

async function run() {
  await mongoose.connect(MONGODB_URI, { serverSelectionTimeoutMS: 30000 });
  console.log('✅ MongoDB 連線成功');

  let added = 0, skipped = 0;
  for (const w of newWords) {
    const exists = await Vocabulary.findOne({ word: { $regex: `^${w.word}$`, $options: 'i' } });
    if (exists) { skipped++; continue; }
    await Vocabulary.create(w);
    added++;
  }

  const total = await Vocabulary.countDocuments();
  console.log(`✅ 新增 ${added} 個單字，跳過 ${skipped} 個重複`);
  console.log(`📚 資料庫現有 ${total} 個單字`);
  await mongoose.disconnect();
}

run().catch(err => { console.error(err); process.exit(1); });
